### ISSUE TITLE
"Simplenote" has been used

### ISSUE THREAD

**Issue by invzhi** [LeeReindeer/SimpleNote#3]
[Simplenote](https://simplenote.com/) is a great app for Android, iOS, macOS, Windows.
Maybe you have a more creative name for your awesome app.

**Comment by LeeReindeer** [comment]
@invzhi Thank you for your suggestion.I know this app and used to use it.Therefore, I use this name.But my rubbish work has no correlation with it, and won't use in business.So I won't change it.just for fun.
